### ISSUE TITLE
Disappointing affiliate linking

### ISSUE THREAD

**Issue by VaughnGH** [datasciencemasters/go#97]
It's unfortunate that a project touting "ebooks... [that are] all free and open" links almost exclusively to for-purchase texts using Amazon affiliate linking, rather than actually linking to the many _free_ and _open_ texts out there.

**Comment by clarecorthell** [comment]
Yep, some content is only available from publishers, in part because the authors are paid to spend months and years creating that content. I, for one, and deeply and eternally grateful to the developers and content creators who *have* created open source and accessible tools that create unmeasurable value for people in research, companies, and hobbyists anywhere in the world, especially this [group](https://github.com/pydata/pandas/graphs/contributors). But not everything is created that way. I personally am grateful for all that *does* exist as open and free.

As someone who's observed this, you can practice being free and open yourself by creating and contributing to open source. I appreciate constructive criticism of what open source materials could replace paid materials in the OSDSM.

**Comment by kylerbrown** [comment]
Hi Clare,
I think the concern is that, by using affiliate links you have a financial conflict of interest. This may cause some people to question whether the linked resources where chosen solely on their educational merits, and may lessen the perceived quality of your project.

I can think of two solutions:
1. Remove the affiliate links, use regular links instead
2. Link instead to WorldCat, where people can find books in their local libraries. ([example](https://www.worldcat.org/title/data-analysis-with-open-source-tools/oclc/780425356)) 

The OP was a bit hostile, but I think he raises a valid concern. Thanks for all your work on this project, I've found it to be an excellent resource.
